"""
Canonical sample schema for the AI Defense Lab project.

Keep this consistent across all sub-topics on the team so datasets can be
merged before the shared detector/eval phase.
"""

from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any
import uuid


VALID_LABELS = (0, 1)  # 0 = legitimate, 1 = fraud/attack

VALID_CHANNELS = ("email", "sms", "chat", "voice_transcript")

VALID_SUBTYPES = (
    "urgency_otp",              # "your OTP will expire, share it now"
    "brand_spoof",               # impersonates bank/payment brand identity
    "authority_impersonation",   # fake bank official / manager / law enforcement
    "reward_lure",                # fake cashback, refund, prize
    "account_verification",      # fake "verify your account or it will be locked"
    "adaptive_conversational",   # dynamic multi-turn social engineering
    "public_spam",                # real-world fraud/spam from a public holdout dataset,
                                    # not generated by us and not mapped to our own subtypes
    "legit",                     # not an attack (negative class)
)

VALID_DIFFICULTY = ("naive", "moderate", "adaptive", "adversarial")
# "adversarial" specifically marks attacks generated to evade a CURRENT trained
# detector's known trigger terms (Phase 5's arms-race loop) -- distinct from
# "adaptive", which just means "written to be subtly convincing" in general,
# with no specific detector in mind.


@dataclass
class Sample:
    text: str
    label: int  # 0 or 1, see VALID_LABELS
    channel: str  # see VALID_CHANNELS
    attack_subtype: str  # see VALID_SUBTYPES
    difficulty_tier: str = "naive"  # see VALID_DIFFICULTY
    source_topic: str = "social_engineering_phishing"  # sub-topic owner, for merging team data
    persona: Optional[Dict[str, Any]] = None
    generation_model: Optional[str] = None
    turn_number: Optional[int] = None  # for conversational samples
    dialogue_id: Optional[str] = None  # groups turns of the same conversation
    id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def validate(self):
        assert self.label in VALID_LABELS, f"invalid label: {self.label}"
        assert self.channel in VALID_CHANNELS, f"invalid channel: {self.channel}"
        assert self.attack_subtype in VALID_SUBTYPES, f"invalid subtype: {self.attack_subtype}"
        assert self.difficulty_tier in VALID_DIFFICULTY, f"invalid difficulty: {self.difficulty_tier}"
        assert isinstance(self.text, str) and len(self.text.strip()) > 0, "empty text"
        return True

    def to_dict(self):
        return asdict(self)
